// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task8.Data.Data;

#nullable disable

namespace Task8.Data.Migrations
{
    [DbContext(typeof(Task6Context))]
    partial class Task6ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task8.Data.Entity.Generated.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("CourseId")
                        .HasName("PK__COURSES__71CB31DB72DA58AE");

                    b.ToTable("COURSES", (string)null);
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("GroupId")
                        .HasName("PK__GROUPS__3EFEA3DE170855A6");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("GROUPS", (string)null);
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("StudentId")
                        .HasName("PK__STUDENTS__E69FE77B55722B59");

                    b.HasIndex("GroupId");

                    b.ToTable("STUDENTS", (string)null);
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Group", b =>
                {
                    b.HasOne("Task8.Data.Entity.Generated.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__GROUPS__NAME__398D8EEE");

                    b.HasOne("Task8.Data.Entity.Generated.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Student", b =>
                {
                    b.HasOne("Task8.Data.Entity.Generated.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__STUDENTS__LAST_N__3C69FB99");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Task8.Data.Entity.Generated.Teacher", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
